version: "3.4"

services:
  nextjs-dev:
    container_name: nextjs-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    entrypoint: yarn dev
    volumes:
      - ./source:/app
      - /app/node_modules
      - /app/.next
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "1"
    environment:
      - NODE_ENV=development
      - TZ=Asia/Jakarta
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    networks:
      - bridge

networks:
  bridge:
    driver: bridge