FROM public.ecr.aws/docker/library/node:20-alpine

# Install apk alpine
RUN apk --update --no-cache add curl tzdata

# Set Timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

# Set Environment
ENV PATH /app/node_modules/.bin:$PATH

# Set Working Directory
WORKDIR /app

# Install Yarn
RUN npm install -g yarn --force

# Copy your files to container
COPY ./source .
RUN yarn

EXPOSE 3000

CMD [ "yarn", "dev" ]